package com.zxg.mybatis;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.d_id
     *
     * @mbggenerated Fri Jun 09 17:13:51 GMT+08:00 2017
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_name
     *
     * @mbggenerated Fri Jun 09 17:13:51 GMT+08:00 2017
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.d_id
     *
     * @return the value of department.d_id
     *
     * @mbggenerated Fri Jun 09 17:13:51 GMT+08:00 2017
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.d_id
     *
     * @param dId the value for department.d_id
     *
     * @mbggenerated Fri Jun 09 17:13:51 GMT+08:00 2017
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_name
     *
     * @return the value of department.dept_name
     *
     * @mbggenerated Fri Jun 09 17:13:51 GMT+08:00 2017
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_name
     *
     * @param deptName the value for department.dept_name
     *
     * @mbggenerated Fri Jun 09 17:13:51 GMT+08:00 2017
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    public Department() {
    }

    public Department(Integer dId, String deptName) {
        this.dId = dId;
        this.deptName = deptName;
    }

    @Override
    public String toString() {
        return "Department{" +
                "dId=" + dId +
                ", deptName='" + deptName + '\'' +
                '}';
    }
}